# Generated by Django 4.1.2 on 2022-10-27 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artiste',
            fields=[
                ('First_Name', models.CharField(max_length=400)),
                ('Last_Name', models.CharField(max_length=400)),
                ('Artiste_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Followers', models.IntegerField()),
                ('Monthly_Listeners', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Song_Title', models.CharField(max_length=400)),
                ('Date_Released', models.DateField()),
                ('Likes', models.IntegerField()),
                ('Song_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MusicApp.artiste')),
            ],
        ),
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.TextField()),
                ('Song_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MusicApp.song')),
            ],
        ),
    ]
