# Generated by Django 4.1.2 on 2022-10-27 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MusicApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='Song_ID',
        ),
        migrations.AddField(
            model_name='song',
            name='Artiste',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='MusicApp.artiste'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lyrics',
            name='Song_ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='MusicApp.song'),
        ),
    ]
