# Generated by Django 4.1.2 on 2022-10-27 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MusicApp', '0002_remove_song_song_id_song_artiste_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artiste',
            old_name='First_Name',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='artiste',
            name='Last_Name',
        ),
    ]
